# for more information visit https://github.com/cedric05/docker-python3.9
FROM ghcr.io/cedric05/python:3.10.2 as builder

ARG VERSION
LABEL maintainer="kesavarapu.siva@gmail.com"
RUN apt update && apt install zip
RUN pip install pyinstaller 
RUN pip uninstall python-magic -y
RUN pip install git+https://github.com/cedric05/dothttp.git
WORKDIR /app
ADD . /app 
RUN wget https://raw.githubusercontent.com/cedric05/dothttp/dev/dothttp/http.tx
RUN pyinstaller --distpath dist ./cli.py --add-data 'http.tx:.'  \
    && cd dist/ && zip -r ../cli.zip cli/  \
    && cd .. && rm -rf dist build
