name: Release prod Artifacts
on:
  push:
    # branches:
    #   - main
    tags:
      - v*
env:
  dothttpversion: 0.0.42a8
  EXTENSION_VERSION: 0.0.42a8
jobs:
  push-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11.0"
          architecture: "x64"
      - name: install dothttp-req
        shell: powershell
        run: |
          pip install dothttp_req==${{ env.dothttpversion }} pyinstaller
          Invoke-WebRequest -Uri https://raw.githubusercontent.com/cedric05/dothttp/v${{ env.dothttpversion }}/dothttp/http.tx -OutFile http.tx
          Invoke-WebRequest -Uri https://raw.githubusercontent.com/cedric05/dothttp/v${{ env.dothttpversion }}/dothttp/postScript.js -OutFile postScript.js
          pyinstaller --distpath dist .\cli.py --add-data 'http.tx;.' --add-data 'postScript.js;.'
          Compress-Archive -DestinationPath dotextensions-x86-windows.zip  -Path  dist\cli
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: |
          dir
          cd test
          npm install
          npx tsc
          npx cross-env CLI_PATH=..\dist\\cli\\cli.exe npx mocha out\test\*.js 
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: dotextensions-${{ env.EXTENSION_VERSION }}-x86-windows.zip
          file: dotextensions-x86-windows.zip
          tag: v-${{ env.EXTENSION_VERSION }}
          overwrite: true
  pushlinux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
            image: tonistiigi/binfmt:latest
            platforms: all
      - name: Download latest earthly
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.6.19/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"  
      - name: Build image
        run: |
          earthly +save-all --VERSION=${{ env.dothttpversion }}
          mv cli-linux/amd64.zip cli-amd64.zip
          mv cli-linux/arm64.zip cli-arm64.zip
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: |
          ls 
          unzip cli-amd64.zip
          export CLI_PATH=$(realpath cli/cli)
          cd test
          npm install
          npx tsc
          npx mocha out/test/*.js 
      - name: Upload arm64 binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: dotextensions-${{ env.EXTENSION_VERSION }}-linux-arm64.zip
          file: cli-arm64.zip
          tag: v-${{ env.EXTENSION_VERSION }}
          overwrite: true
      - name: Upload amd64 binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: dotextensions-${{ env.EXTENSION_VERSION }}-linux-amd64.zip
          file: cli-amd64.zip
          tag: v-${{ env.EXTENSION_VERSION }}
          overwrite: true
  push-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11.0"
          architecture: "x64"
      - name: install dothttp
        run: |
          pip install pyinstaller 
          pip install dothttp_req==${{ env.dothttpversion }}
          wget https://raw.githubusercontent.com/cedric05/dothttp/v${{ env.dothttpversion }}/dothttp/http.tx
          wget https://raw.githubusercontent.com/cedric05/dothttp/v${{ env.dothttpversion }}/dothttp/postScript.js
          pyinstaller --distpath dist ./cli.py --add-data 'http.tx:.' --add-data 'postScript.js:.'  \
              && cd dist/ && zip -r ../cli.zip cli/  \
              && cd .. && rm -rf dist build
          cp cli.zip dothttp-cli.zip
      # - name: Use Node.js 14.x
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 14.x
      # - run: |
      #     ls 
      #     unzip dothttp-cli.zip
      #     export CLI_PATH=$(pwd)/cli/cli
      #     cd test
      #     npm install
      #     npm install typescript@latest
      #     npx tsc
      #     npx mocha out/test/*.js 
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: dotextensions-${{ env.EXTENSION_VERSION }}-darwin.zip
          file: cli.zip
          tag: v-${{ env.EXTENSION_VERSION }}
          overwrite: true
