name: release builds
on:
  push:
    branches:
      - main
    tags:
      - v*
env:
  dothttpversion: 0.0.7
jobs:
  push:
    runs-on: windows-2019
    if: github.event_name == 'ram'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.1"
          architecture: "x64"
      - name: install dothttp-req
        shell: powershell
        run: |
          pip install dothttp_req==${{ env.dothttpversion }} pyinstaller
          pyinstaller --distpath dist .\cli.py --add-data 'http.tx;.'
          Compress-Archive -DestinationPath dotextensions-x86-windows.zip  -Path  dist\cli
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: dotextensions-${{ env.dothttpversion }}-x86-windows.zip
          file: dotextensions-x86-windows.zip
          tag: v-${{ env.dothttpversion }}
          overwrite: true
          file_glob: true
  pushlinux:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build image
        run: |
          docker build --tag dotextensions --build-arg ${{ env.dothttpversion }} .
          docker run --rm --entrypoint cat dotextensions  /app/cli.zip > dothttp-cli.zip
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: dotextensions-${{ env.dothttpversion }}-linux.zip
          file: dothttp-cli.zip
          tag: v-${{ env.dothttpversion }}
          overwrite: true
          file_glob: true
